config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users, controllers: {
                    registrations: 'users/registrations',
                    sessions: 'users/sessions'}
  resources :users #, only: [:index, :update]
  resources :stories
  root 'stories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">PicStory</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-circle-o" style="font-size:24px""></i>
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%=link_to 'Create PicStory', new_story_path %></li>
            <li><%=link_to 'My PicStory', users_path %></li>
            <li><%=link_to 'My Profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to 'Sign Out', destroy_user_session_path %></li>
          <% else %>
            <li><%=link_to 'Log In', new_user_session_path %></li>         
            <li><%=link_to 'Registration', new_user_registration_path %></li>
          <% end %>

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>