config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users, controllers: {
                    registrations: 'users/registrations',
                    sessions: 'users/sessions'}
  resources :users #, only: [:index, :update]
  resources :stories
  root 'stories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find params[:id]
  end


  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params.merge(user: current_user))

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    if current_user.admin? || @story.user == current_user
      respond_to do |format|
        if @story.update(story_params)
          format.html { redirect_to @story, notice: 'Story was successfully updated.' }
          format.json { render :show, status: :ok, location: @story }
        else
          format.html { render :edit }
          format.json { render json: @story.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to stories_url, notice: "you are not allowed to edit this story" 
    end
  end


  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    if current_user.admin? || @story.user == current_user
      @story.destroy
      respond_to do |format|
        format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to stories_url, notice: "you are not allowed to destroy this story"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :picture, :content, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>   

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :story_picture %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :story_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>PicStories</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-1">
    <%= link_to 'New story', new_story_path, class: "btn btn-info btn-sm" %>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-1">
    <%= link_to 'Admin Panel', admin_index_path, class: "btn btn-info btn-sm" %>
  </div>
</div>

<div class="row">
<% if user_signed_in? %>
  <% @stories.reverse.each do |story| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(story.picture), story) if story.picture? %>
        <div class="caption">
          <h3><%= story.title %></h3>
          <small><%= time_ago_in_words(story.created_at) %> ago</small>
          <p><%= story.content.truncate(150)  %></p>
          
            <p>
            <%= link_to 'Show', story, class: "btn btn-primary" %> 
            <% if user_signed_in? && user_signed_in? == current_user %>
            <%= link_to 'Edit', edit_story_path(story), class: "btn btn-warning" %> 
            <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
            </p>
            

        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <%= redirect_to root_path %>
<% end %>
</div>


<br>

app/views/stories/new.html.erb
<h1>Editing PicStory</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= image_tag(@story.picture, style: "max-width: 100%; border-radius: 10px;") if @story.picture? %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <h1><%= @story.title %></h1>
          <small><%= time_ago_in_words(@story.created_at) %> ago</small>
        </div>
        <div class="col-md-2"></div>
      </div>

      <hr>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <p><%= @story.content %></p>
          <p> Escrito por: <%= @story.user %></p>
        </div>
        <div class="col-md-2"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-2">
        <%= link_to 'Back', stories_path, class: "btn btn-info btn-sm" %></p>
        <% if user_signed_in? && @story.user_id == current_user.id %>
          <p><%= link_to 'Edit', edit_story_path(@story), class: "btn btn-warning btn-sm" %> 
        <% end %>
        </div>
        <div class="col-md-2"></div>
      </div>

</div>